apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  replicas: 4
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      hostNetwork: true
      containers:
        - name: tf-serving
          image: {{ .Values.deploy.image }}
          {{- if ne .Values.deploy.modelConfig "nil" }}
          args:
            - '--model_config_file={{ .Values.deploy.modelConfig }}'
          {{- end }}
          ports:
            - containerPort: 8501
              name: rest
            - containerPort: 8500
              name: grpc
          volumeMounts:
            - name: model
              mountPath: /models
              subPath: {{ .Values.deploy.storage.nfs.subPath }}
          resources:
            requests:
              cpu: {{ .Values.deploy.resources.requests.cpu }}
              memory: {{ .Values.deploy.resources.requests.memory }}
            limits:
              cpu: {{ .Values.deploy.resources.limits.cpu }}
              memory: {{ .Values.deploy.resources.limits.memory }}
      volumes:
        - name: model
          nfs:
            server: {{ .Values.deploy.storage.nfs.server }}
            path: {{ .Values.deploy.storage.nfs.path }}
            readOnly: {{ .Values.deploy.storage.nfs.readOnly }}
