version: '3'
services:
  ml-base:
    image: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-${PACKAGE_OPTION:-pip}-py${PYTHON_VERSION:-3.10}-scikit-learn-${SCIKIT_VERSION:-2023.1.1}-xgboost-${XGBOOST_VERSION:-1.7.5}
    pull_policy: always
    build:
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        no_proxy: ${no_proxy}
        BASE_IMAGE_NAME: ${BASE_IMAGE_NAME:-ubuntu}
        BASE_IMAGE_TAG: ${BASE_IMAGE_TAG:-22.04}
        MINICONDA_VERSION: ${MINICONDA_VERSION:-latest-Linux-x86_64}
        PACKAGE_OPTION: ${PACKAGE_OPTION:-pip}
        PYTHON_VERSION: ${PYTHON_VERSION:-3.10}
        SCIKIT_VERSION: ${SCIKIT_VERSION:-2023.1.1}
        XGBOOST_VERSION: ${XGBOOST_VERSION:-1.7.5}
      # context: classical-ml
      target: ml-base-${PACKAGE_OPTION:-pip}
    command: >
      bash -c "python -c 'import sklearnex, sklearn; import xgboost as xgb; print(\"Scikit version:\", sklearn.__version__, \"\\nXGBoost version:\", xgb.__version__)'"
