version: '3'
services:
  tf-base:
    build:
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        no_proxy: ${no_proxy}
        BASE_IMAGE_NAME: ${BASE_IMAGE_NAME:-ubuntu}
        BASE_IMAGE_TAG: ${BASE_IMAGE_TAG:-22.04}
        PACKAGE_OPTION: ${PACKAGE_OPTION:-pip}
        PYTHON_VERSION: ${PYTHON_VERSION:-3.10}
        MINICONDA_VERSION: ${MINICONDA_VERSION:-latest-Linux-x86_64}
        TF_PACKAGE_VERSION: ${TF_PACKAGE_VERSION:-2.12.0}
        TF_PACKAGE: ${TF_PACKAGE:-intel-tensorflow}
      target: tf-base-${PACKAGE_OPTION:-pip}
      # context: tensorflow
    command: >
      bash -c "env && python -c 'import tensorflow as tf; print(\"Tensorflow Version:\", tf.__version__)'"
    image: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-${PACKAGE_OPTION:-pip}-py${PYTHON_VERSION:-3.10}-${TF_PACKAGE:-intel-tensorflow}-${TF_PACKAGE_VERSION:-2.12.0}-base
    pull_policy: always

  jupyter:
    build:
      target: jupyter
    extends: tf-base
    command: >
      bash -c "python -m jupyter --version"
    image: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-${PACKAGE_OPTION:-pip}-py${PYTHON_VERSION:-3.10}-${TF_PACKAGE:-intel-tensorflow}-${TF_PACKAGE_VERSION:-2.12.0}-jupyter

  inc:
    build:
      args:
        HOROVOD_VERSION: ${HOROVOD_VERSION:-0.28.0}
        INC_VERSION: ${INC_VERSION:-2.1.1}
        MPI: ${MPI:-openmpi}
      target: inc
    extends: tf-base
    command: >
      bash -c "mpirun --version && python -c 'import neural_compressor, tf2onnx; print(\"\\nNeural Compressor Version:\", neural_compressor.__version__, \"\\\nTensorFlow2ONNX Version:\", tf2onnx.__version__)'"
    image: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-${PACKAGE_OPTION:-pip}-py${PYTHON_VERSION:-3.10}-${TF_PACKAGE:-intel-tensorflow}-${TF_PACKAGE_VERSION:-2.12.0}-${MPI:-openmpi}-horovod-${HOROVOD_VERSION:-0.28.0}-inc-${INC_VERSION:-2.1.1}
