name: Container Builder
on:
  workflow_dispatch:
    inputs:
      dir: 
        required: true
        type: string
      env_overrides: 
        required: false
        type: string

jobs:
  build:
    uses: ./.github/workflows/compose-module.yml
    with:
      dir: ${{ github.event.inputs.dir }}
      env_overrides: ${{ github.event.inputs.env_overrides }}
