name: PyTorch Base Ingredient Containers Build
on: 
  workflow_dispatch:
    inputs:
      package_option: 
        default: "pip"
        required: true
        type: choice
        options: 
        - "pip"
        - "idp"
      ipex_package_version:
        default: "2.0.0"
        required: false
        type: string
      other_version: 
        required: false
        type: string
  workflow_call:
    inputs:
      ipex_package_version:
        default: "2.0.0"
        required: false
        type: string
      other_version: 
        required: false
        type: string

jobs:
  base-framework-build:
    container:
      image: ${{ vars.REGISTRY }}/aiops/compose-dev
      env:
        http_proxy: ${{ secrets.HTTP_PROXY }}
        https_proxy: ${{ secrets.HTTPS_PROXY }}
        no_proxy: ${{ secrets.NO_PROXY }}
      credentials:
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_TOKEN }}
    strategy:
      matrix:
        package_option: [ "pip", "idp" ]
        experimental: [ true ]
      fail-fast: false
    runs-on: [ aia-devops ]
    steps: 
    - uses: actions/checkout@v3
    - uses: docker/login-action@v2
      with:
        username: ${{ secrets.HUB_USER }}
        password: ${{ secrets.HUB_TOKEN }}
    - uses: docker/login-action@v2
      with:
        registry: ${{ vars.REGISTRY }}
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_TOKEN }}
    - name: Remove Containers
      run: docker compose down
      working-directory: pytorch
    - name: Build Framework Ingredient Containers
      run: |
        IPEX_VERSION=${{ github.event.input.ipex_package_version }} \
        PACKAGE_OPTION=${{ matrix.package_option }} \
        REGISTRY=${{ vars.REGISTRY }} \
        ${{ github.event.input.other_version }} docker compose up --build --force-recreate
      working-directory: pytorch
    - name: Push Framework Ingredient Containers
      run: |
        IPEX_VERSION=${{ github.event.input.ipex_package_version }} \
        PACKAGE_OPTION=${{ matrix.package_option }} \
        REGISTRY=${{ vars.REGISTRY }} \
        ${{ github.event.input.other_version }} docker compose push --ignore-push-failures
      working-directory: pytorch
