name: Tensorflow Base Ingredient Containers Build
on: 
  workflow_dispatch:
    inputs:
      tf_package_version:
        default: "2.12.0"
        required: false
        type: string
      other_version: 
        required: false
        type: string
  workflow_call:
    inputs:
      tf_package_version:
        default: "2.12.0"
        required: false
        type: string
      other_version: 
        required: false
        type: string
jobs:
  base-framework-build:
    container:
      image: ${{ vars.REGISTRY }}/aiops/compose-dev
      env:
        http_proxy: ${{ secrets.HTTP_PROXY }}
        https_proxy: ${{ secrets.HTTPS_PROXY }}
        no_proxy: ${{ secrets.NO_PROXY }}
      credentials:
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_TOKEN }}
    strategy:
      matrix:
        tf_package: ["intel-tensorflow", "intel-tensorflow-avx512"]
        mpi_package: [ "mpich", "openmpi" ]
        package_option: [ "pip", "idp" ]
        experimental: [ true ]
      fail-fast: false
    runs-on: [ aia-devops ]
    steps: 
    - uses: actions/checkout@v3
      with:
        submodules: true
        set-safe-directory: true
    - uses: docker/login-action@v2
      with:
        username: ${{ secrets.HUB_USER }}
        password: ${{ secrets.HUB_TOKEN }}
    - uses: docker/login-action@v2
      with:
        registry: ${{ vars.REGISTRY }}
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_TOKEN }}
    - name: Remove Containers
      run: docker compose down
      working-directory: tensorflow
    - name: Build Framework Ingredient Containers
      run: |
        MPI=${{ matrix.mpi_package }} \
        PACKAGE_OPTION=${{ matrix.package_option }} \
        REGISTRY=${{ vars.REGISTRY }} \
        TF_PACKAGE_VERSION=${{ github.event.input.tf_package_version }} \
        TF_PACKAGE=${{ matrix.tf_package }} \
        ${{ github.event.input.other_version }} docker compose up --build --force-recreate
      working-directory: tensorflow
    - name: Push Framework Ingredient Containers
      run: |
        MPI=${{ matrix.mpi_package }} \
        PACKAGE_OPTION=${{ matrix.package_option }} \
        REGISTRY=${{ vars.REGISTRY }} \
        TF_PACKAGE_VERSION=${{ github.event.input.tf_package_version }} \
        TF_PACKAGE=${{ matrix.tf_package }} \
        ${{ github.event.input.other_version }} docker compose push
      working-directory: tensorflow

