name: Container Test Workflow
on: 
  workflow_call:
    inputs:
      parent_dir: 
        required: true
        type: string
      dir: 
        required: true
        type: string
      runner_label:
        required: true
        type: string

jobs:
  test-containers:
    runs-on: [ self-hosted, Linux, "${{ inputs.runner_label }}"]
    steps: 
    - uses: actions/checkout@v4
    - uses: docker/login-action@v2
      with:
        registry: ${{ vars.REGISTRY }}
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_TOKEN }}
    - name: Test Containers
      run: |
        python -m venv venv
        source venv/bin/activate
        python -m pip install -r ${{ github.workspace }}/test-runner/requirements.txt
        python ${{ github.workspace }}/test-runner/test_runner.py -f ${{ inputs.parent_dir }}/${{ inputs.dir }}/tests.yaml -l ${{ github.workspace }}/${{ inputs.parent_dir }}/${{ inputs.dir }}/logs
      env:
        PYTHONPATH: ${{ github.workspace }}
        REGISTRY: ${{ vars.REGISTRY }}
        GITHUB_RUN_NUMBER: ${{ github.run_number }}
    - name: Print Log Summary
      if: always()
      run: echo -e "\`\`\`\n$(cat ${{ inputs.parent_dir }}/${{ inputs.dir }}/logs/test-runner.log)\n\`\`\`" >> $GITHUB_STEP_SUMMARY
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: ${{ inputs.dir }} outputs
        path: ${{ github.workspace }}/${{ inputs.parent_dir }}/${{ inputs.dir }}/logs
